import { fromHtml } from "hast-util-from-html";
import { toMarkdown } from "mdast-util-to-markdown";
import { toMdast } from "hast-util-to-mdast";
import { toHast } from "mdast-util-to-hast";
import { toHtml } from "hast-util-to-html";
import { fromMarkdown } from "mdast-util-from-markdown";
import { gfmToMarkdown, gfmFromMarkdown } from "mdast-util-gfm";
import { directive } from "micromark-extension-directive";
import {
  directiveFromMarkdown,
  directiveToMarkdown,
} from "mdast-util-directive";
import { gfm } from "micromark-extension-gfm";

/**
 * Converts an HTML string to Markdown.
 * Includes support for GFM and Directives (Admonitions) to ensure
 * compatibility with MDXEditor's rich text features.
 *
 * @param htmlString The HTML string to convert.
 * @returns The Markdown representation of the HTML.
 */
export function htmlToMarkdown(htmlString: string): string {
  if (!htmlString || htmlString.trim() === "") {
    return "";
  }

  // Parse HTML into HAST (Hypertext Abstract Syntax Tree)
  const hast = fromHtml(htmlString, { fragment: true });

  // Transform HAST to MDAST (Markdown Abstract Syntax Tree)
  // We use a custom nodeHandler to strip out all HTML comments (e.g., <!--TgQPHd|[]-->)
  // generated by external sources like Google Docs or internal metadata.
  const mdast = toMdast(hast, {
    nodeHandlers: {
      comment: () => undefined,
    },
  });

  // Serialize MDAST to Markdown string
  let markdown = toMarkdown(mdast, {
    extensions: [gfmToMarkdown(), directiveToMarkdown()],
    bullet: "-",
    emphasis: "_",
    ruleSpaces: true,
  });

  // Remove excessive newlines
  markdown = markdown.replace(/\n{3,}/g, "\n\n");

  return markdown;
}

/**
 * Heuristic check to determine if text is likely Markdown.
 * * It checks if the parsed AST contains structural elements beyond a single
 * plain text paragraph (e.g., headings, lists, code blocks, or inline links/formatting).
 * * @param text The string to check.
 * @returns true if the text contains structural Markdown elements.
 */
export function isMarkdownText(text: string): boolean {
  // Ignore empty or extremely short strings that can't be meaningful MD
  if (!text || text.trim().length < 3) {
    return false;
  }

  try {
    // Parse using the same extensions used for conversion to ensure consistency
    const tree = fromMarkdown(text, {
      extensions: [directive(), gfm()],
      mdastExtensions: [gfmFromMarkdown(), directiveFromMarkdown()],
    });

    // Heuristic: Does the AST contain anything more complex than a plain paragraph?
    const hasMarkdownStructures = tree.children.some((node) => {
      // Non-paragraph nodes (Heading, List, Table, Code, etc.) are definitive
      if (node.type !== "paragraph") {
        return true;
      }

      // If it is a paragraph, check children for inline formatting (Link, Strong, Emphasis, etc.)
      if ("children" in node && Array.isArray(node.children)) {
        return node.children.some(
          (child) => child.type !== "text" && child.type !== "break",
        );
      }
      return false;
    });

    return hasMarkdownStructures;
  } catch (error) {
    // If the parser fails, assume it's not valid/standard Markdown
    console.log(error);
    return false;
  }
}

/**
 * Converts an HTML string into Clean Basic HTML.
 * Uses the MDAST pipeline to strip out bloat.
 *
 * @param htmlString The bloated HTML string to clean.
 * @returns Clean, simplified HTML string.
 */
export function htmlToCleanHtml(htmlString: string): string {
  if (!htmlString || htmlString.trim() === "") {
    return "";
  }

  // Parse HTML into HAST (Hypertext Abstract Syntax Tree)
  const hast = fromHtml(htmlString, { fragment: true });

  // Transform HAST to MDAST (Markdown Abstract Syntax Tree) to strip bloat
  // Explicitly ignore comment nodes to ensure no HTML comments leak into the final output.
  const mdast = toMdast(hast, {
    nodeHandlers: {
      comment: () => undefined,
    },
  });

  // Transform MDAST back to HAST (Clean HAST)
  // Disable common behaviors that might inject positional or unneeded data if necessary
  const cleanHast = toHast(mdast);

  if (!cleanHast) {
    return "";
  }

  // Serialize Clean HAST to HTML string
  const cleanHtml = toHtml(cleanHast as Parameters<typeof toHtml>[0]);

  return cleanHtml;
}

/**
 * Converts a Markdown string into Clean Basic HTML.
 * Uses the MDAST pipeline.
 *
 * @param markdown The Markdown string.
 * @returns Clean, simplified HTML string.
 */
export function markdownToCleanHtml(markdown: string): string {
  if (!markdown || markdown.trim() === "") {
    return "";
  }

  // Parse Markdown into MDAST
  const mdast = fromMarkdown(markdown, {
    extensions: [directive(), gfm()],
    mdastExtensions: [gfmFromMarkdown(), directiveFromMarkdown()]
  });

  // Transform MDAST to HAST (Clean HAST)
  const cleanHast = toHast(mdast);

  if (!cleanHast) {
    return "";
  }

  // Serialize Clean HAST to HTML string
  const cleanHtml = toHtml(cleanHast as Parameters<typeof toHtml>[0]);

  return cleanHtml;
}
